version: "3"
services:
  pythonapp:
    build: ./worker/
    command: sh -c "sleep 10s ; python3 ./worker.py"
    depends_on:
      - mysql

  mysql:
    build: ./database/
    restart: always 
    environment:
      MYSQL_DATABASE: 'STOCKS'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'