apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql
spec:
 replicas: 1
 selector:
   matchLabels:
     app: mysql
 strategy:
   type: Recreate
 template:
   metadata:
     labels:
       app: mysql
   spec:
     containers:
     - image: juliakush01/mysql
       name: mysql
       env:
       - name: MYSQL_ROOT_PASSWORD
         value: my-secret-pw
       ports:
         - name: http-port
           containerPort: 3306
