FROM python:2.7
WORKDIR /app
ADD . /app
ADD odbcinst.ini /etc/odbcinst.ini
RUN apt-get update
RUN apt-get install -y tdsodbc unixodbc-dev
RUN apt install unixodbc-bin -y
RUN apt-get clean -y
RUN pip install -r requirements.txt
COPY . .
CMD ["python3", "worker.py"]
