FROM python:3.9
ADD requirements.txt .
RUN pip install mysql-connector-python
RUN pip install -r requirements.txt
WORKDIR /usr/app/src
COPY worker.py ./
COPY . .
RUN pip install mysql-connector-python
RUN pip install -r requirements.txt
CMD ["python", "worker.py"]
