apiVersion: apps/v1
kind: Deployment
metadata:
 name: worker
spec:
 replicas: 1
 selector:
   matchLabels:
     app: python
 strategy:
   type: Recreate
 template:
   metadata:
     labels:
       app: python
   spec:
     containers:
     - image: python:2.7
       name: worker
       ports:
           - containerPort: 3308
