FROM node:latest
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip3 install pandas && \
    pip3 install cufflinks && \
    pip3 install numpy && \
    pip3 install requests
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 8080
CMD ["node", "main.js"]